// Trademark Gazette redesign — fake but plausible data
// Vietnamese-flavored: NOIP gazette terminology (T1-T4 weekly issues, A=applications, B=registrations)

window.NICE_CLASSES = {
  1: { group: "goods", label: "Chemicals" },
  3: { group: "goods", label: "Cosmetics, cleaning" },
  5: { group: "goods", label: "Pharmaceuticals" },
  7: { group: "goods", label: "Machines" },
  9: { group: "goods", label: "Software, electronics" },
  10: { group: "goods", label: "Medical apparatus" },
  11: { group: "goods", label: "Lighting, heating" },
  25: { group: "goods", label: "Clothing, footwear" },
  29: { group: "goods", label: "Meat, dairy, processed food" },
  30: { group: "goods", label: "Coffee, foodstuffs" },
  32: { group: "goods", label: "Beverages, beer" },
  33: { group: "goods", label: "Wine, spirits" },
  35: { group: "services", label: "Services & advertising" },
  36: { group: "services", label: "Insurance & financial" },
  38: { group: "services", label: "Telecommunications" },
  41: { group: "services", label: "Education, entertainment" },
  42: { group: "services", label: "Scientific services" },
  43: { group: "services", label: "Hotels & restaurants" },
  44: { group: "services", label: "Medical services" },
};

// Mark specimen "renderers" — keys map to MarkSpecimen styles
// figurative = stylized monogram, wordmark = typographic treatment
window.TRADEMARKS = [
  {
    id: "tm-001",
    name: "NEUROFAX",
    applicant: "PHARMASIA HOLDINGS INC.",
    applicantType: "company",
    country: "SG",
    countryName: "Singapore",
    appNo: "4-2025-71204",
    certNo: null,
    type: "A",
    typeLabel: "Application",
    classes: [5, 10],
    publishedAt: "2026-04-08",
    filedAt: "2025-08-14",
    examinedAt: "2026-01-22",
    oppositionEnds: "2026-06-08",
    city: "Singapore",
    agent: "WINCO LAW FIRM",
    specimen: { style: "wordmark-sans-bold", color: "ink", text: "NEUROFAX" },
    gazette: "A_T2_2026.pdf",
    page: 1402,
    similarToWatch: { score: 0.94, watchId: "wl-neurex", reason: "Phonetic + class overlap" },
  },
  {
    id: "tm-002",
    name: "NEURAXIS",
    applicant: "Lê Văn Đức",
    applicantType: "personal",
    country: "VN",
    countryName: "Vietnam",
    appNo: "4-2025-49102",
    type: "A",
    typeLabel: "Application",
    classes: [5],
    publishedAt: "2026-04-08",
    filedAt: "2025-09-02",
    examinedAt: "2026-02-12",
    oppositionEnds: "2026-06-08",
    city: "Hà Nội",
    agent: "VPLS BÁCH MINH",
    specimen: { style: "wordmark-serif", color: "ink", text: "NEURAXIS" },
    gazette: "A_T2_2026.pdf",
    page: 1188,
    similarToWatch: { score: 0.86, watchId: "wl-neurex", reason: "Phonetic / Levenshtein 3" },
  },
  {
    id: "tm-003",
    name: "NUROFEN PLUS",
    applicant: "RECKITT BENCKISER HEALTHCARE (UK) LIMITED",
    applicantType: "company",
    country: "GB",
    countryName: "United Kingdom",
    appNo: "4-2025-43887",
    type: "A",
    typeLabel: "Application",
    classes: [5],
    publishedAt: "2026-03-28",
    filedAt: "2025-06-30",
    oppositionEnds: "2026-05-28",
    city: "Slough",
    agent: "T&G IP PARTNERS",
    specimen: { style: "wordmark-rounded", color: "stamp", text: "NUROFEN+" },
    gazette: "A_T1_2026.pdf",
    page: 2104,
    similarToWatch: { score: 0.78, watchId: "wl-neurex", reason: "Visual + class overlap" },
  },
  {
    id: "tm-004",
    name: "MASAN",
    applicant: "CÔNG TY CỔ PHẦN TẬP ĐOÀN MASAN",
    applicantType: "company",
    country: "VN",
    countryName: "Vietnam",
    appNo: "4-2024-00821",
    certNo: "4-0298142",
    type: "B",
    typeLabel: "Registration",
    classes: [29, 30, 32, 35, 43],
    publishedAt: "2026-04-15",
    filedAt: "2024-01-11",
    registeredAt: "2025-11-04",
    expiresAt: "2035-11-04",
    city: "Hồ Chí Minh",
    agent: "VINIP & ASSOCIATES",
    specimen: { style: "wordmark-italic-serif", color: "stamp", text: "MASAN" },
    gazette: "B_T2_2026.pdf",
    page: 88,
  },
  {
    id: "tm-005",
    name: "VINGROUP",
    applicant: "VINGROUP JOINT STOCK COMPANY",
    applicantType: "company",
    country: "VN",
    countryName: "Vietnam",
    appNo: "4-2023-12345",
    certNo: "4-0289741",
    type: "B",
    typeLabel: "Registration",
    classes: [9, 35, 36, 41, 42, 43],
    publishedAt: "2026-04-15",
    filedAt: "2023-04-09",
    registeredAt: "2025-03-08",
    expiresAt: "2035-03-08",
    city: "Hà Nội",
    agent: "VPLS BÁCH MINH",
    specimen: { style: "monogram-V", color: "stamp", text: "VINGROUP" },
    gazette: "B_T2_2026.pdf",
    page: 142,
  },
  {
    id: "tm-006",
    name: "VINAMILK",
    applicant: "CÔNG TY CỔ PHẦN SỮA VIỆT NAM",
    applicantType: "company",
    country: "VN",
    countryName: "Vietnam",
    appNo: "4-2023-09921",
    certNo: "4-0287012",
    type: "B",
    typeLabel: "Registration",
    classes: [29, 30, 32, 35],
    publishedAt: "2026-04-15",
    filedAt: "2023-03-18",
    registeredAt: "2025-02-21",
    expiresAt: "2035-02-21",
    city: "Hồ Chí Minh",
    agent: "—",
    specimen: { style: "wordmark-condensed", color: "ok", text: "VINAMILK" },
    gazette: "B_T2_2026.pdf",
    page: 410,
  },
  {
    id: "tm-007",
    name: "ZENPHARM",
    applicant: "Nguyễn Văn Hiếu",
    applicantType: "personal",
    country: "VN",
    countryName: "Vietnam",
    appNo: "4-2025-63221",
    type: "A",
    typeLabel: "Application",
    classes: [5],
    publishedAt: "2026-02-25",
    filedAt: "2025-10-04",
    oppositionEnds: "2026-04-25",
    city: "Tây Ninh",
    agent: "—",
    specimen: { style: "wordmark-sans-bold", color: "ink", text: "ZENPHARM" },
    gazette: "A_T4_2026.pdf",
    page: 803,
  },
  {
    id: "tm-008",
    name: "BIVAXIS",
    applicant: "Trần Thị Minh Anh",
    applicantType: "personal",
    country: "VN",
    countryName: "Vietnam",
    appNo: "4-2025-55323",
    type: "A",
    typeLabel: "Application",
    classes: [5, 10],
    publishedAt: "2026-02-25",
    filedAt: "2025-09-19",
    oppositionEnds: "2026-04-25",
    city: "Hồ Chí Minh",
    agent: "WINCO LAW FIRM",
    specimen: { style: "wordmark-serif", color: "ink", text: "BIVAXIS" },
    gazette: "A_T4_2026.pdf",
    page: 1011,
    similarToWatch: { score: 0.71, watchId: "wl-vexis", reason: "Suffix match" },
  },
  {
    id: "tm-009",
    name: "AMVITAL",
    applicant: "Phạm Thị Lan Hương",
    applicantType: "personal",
    country: "VN",
    countryName: "Vietnam",
    appNo: "4-2025-41887",
    type: "A",
    typeLabel: "Application",
    classes: [5],
    publishedAt: "2026-02-10",
    filedAt: "2025-08-02",
    oppositionEnds: "2026-04-10",
    city: "Đà Nẵng",
    agent: "—",
    specimen: { style: "wordmark-italic-serif", color: "ink", text: "AMVITAL" },
    gazette: "A_T3_2026.pdf",
    page: 287,
  },
  {
    id: "tm-010",
    name: "SAMSUNG",
    applicant: "SAMSUNG ELECTRONICS CO., LTD.",
    applicantType: "company",
    country: "KR",
    countryName: "South Korea",
    appNo: "4-2023-99812",
    certNo: "4-0298811",
    type: "B",
    typeLabel: "Registration (Madrid)",
    classes: [7, 9, 11, 35, 38, 41, 42],
    publishedAt: "2026-04-15",
    filedAt: "2023-11-30",
    registeredAt: "2025-12-12",
    expiresAt: "2035-12-12",
    city: "Suwon-si",
    agent: "VPLS BÁCH MINH",
    specimen: { style: "wordmark-sans-bold", color: "ink", text: "SAMSUNG" },
    gazette: "B_T2_2026.pdf",
    page: 2847,
  },
  {
    id: "tm-011",
    name: "VEXARIS",
    applicant: "BAYER AKTIENGESELLSCHAFT",
    applicantType: "company",
    country: "DE",
    countryName: "Germany",
    appNo: "4-2025-37001",
    type: "A",
    typeLabel: "Application (Madrid)",
    classes: [5, 10, 44],
    publishedAt: "2026-04-08",
    filedAt: "2025-05-21",
    oppositionEnds: "2026-06-08",
    city: "Leverkusen",
    agent: "T&G IP PARTNERS",
    specimen: { style: "wordmark-condensed", color: "stamp", text: "VEXARIS" },
    gazette: "A_T2_2026.pdf",
    page: 1922,
    similarToWatch: { score: 0.82, watchId: "wl-vexis", reason: "Levenshtein 2 / class match" },
  },
  {
    id: "tm-012",
    name: "VEXIS",
    applicant: "VEXIS LABORATORIES PRIVATE LIMITED",
    applicantType: "company",
    country: "IN",
    countryName: "India",
    appNo: "4-2025-29110",
    type: "A",
    typeLabel: "Application",
    classes: [5],
    publishedAt: "2026-03-28",
    filedAt: "2025-04-02",
    oppositionEnds: "2026-05-28",
    city: "Hyderabad",
    agent: "—",
    specimen: { style: "monogram-circle", color: "ink", text: "VX" },
    gazette: "A_T1_2026.pdf",
    page: 559,
    similarToWatch: { score: 0.95, watchId: "wl-vexis", reason: "Identical root" },
  },
];

window.WATCHLISTS = [
  {
    id: "wl-neurex",
    name: "NEUREX (CR-2024-118)",
    client: "Cresta Pharma SA",
    matter: "CR-2024-118",
    queryDesc: "Phonetic +/- 2 · Classes 5,10 · Worldwide",
    newCount: 3,
    totalCount: 47,
    lastUpdated: "2026-05-19T08:14:00",
  },
  {
    id: "wl-vexis",
    name: "VEXIS family",
    client: "Vexis Health Ltd.",
    matter: "VX-2025-04",
    queryDesc: "Substring \"vex*\" · Classes 5,10,44 · ASEAN+IN",
    newCount: 4,
    totalCount: 23,
    lastUpdated: "2026-05-19T08:14:00",
  },
  {
    id: "wl-masan",
    name: "MASAN portfolio",
    client: "Masan Group",
    matter: "MS-INHOUSE",
    queryDesc: "Visual sim ≥ 0.7 · All food/bev classes · VN+CN",
    newCount: 2,
    totalCount: 132,
    lastUpdated: "2026-05-19T08:14:00",
  },
  {
    id: "wl-mom",
    name: "MoM children brands",
    client: "Internal R&D",
    matter: "RND-MOM",
    queryDesc: "Sound-alike \"moo\" · Class 29,30 · VN",
    newCount: 0,
    totalCount: 8,
    lastUpdated: "2026-05-19T08:14:00",
  },
];

// Opposition windows currently open, sorted by closing date
window.OPPOSITIONS = [
  {
    markId: "tm-009",
    markName: "AMVITAL",
    applicant: "Phạm Thị Lan Hương",
    classes: [5],
    closesAt: "2026-04-10",
    daysLeft: -40, // closed
    status: "closed",
    relevant: false,
  },
  {
    markId: "tm-007",
    markName: "ZENPHARM",
    applicant: "Nguyễn Văn Hiếu",
    classes: [5],
    closesAt: "2026-04-25",
    daysLeft: -25,
    status: "closed",
    relevant: false,
  },
  {
    markId: "tm-008",
    markName: "BIVAXIS",
    applicant: "Trần Thị Minh Anh",
    classes: [5, 10],
    closesAt: "2026-04-25",
    daysLeft: -25,
    status: "closed",
    relevant: false,
    watchId: "wl-vexis",
  },
  {
    markId: "tm-003",
    markName: "NUROFEN PLUS",
    applicant: "Reckitt Benckiser",
    classes: [5],
    closesAt: "2026-05-28",
    daysLeft: 8,
    status: "open",
    relevant: true,
    watchId: "wl-neurex",
  },
  {
    markId: "tm-012",
    markName: "VEXIS",
    applicant: "Vexis Laboratories Pvt. Ltd.",
    classes: [5],
    closesAt: "2026-05-28",
    daysLeft: 8,
    status: "open",
    relevant: true,
    watchId: "wl-vexis",
  },
  {
    markId: "tm-001",
    markName: "NEUROFAX",
    applicant: "Pharmasia Holdings",
    classes: [5, 10],
    closesAt: "2026-06-08",
    daysLeft: 19,
    status: "open",
    relevant: true,
    watchId: "wl-neurex",
  },
  {
    markId: "tm-002",
    markName: "NEURAXIS",
    applicant: "Lê Văn Đức",
    classes: [5],
    closesAt: "2026-06-08",
    daysLeft: 19,
    status: "open",
    relevant: true,
    watchId: "wl-neurex",
  },
  {
    markId: "tm-011",
    markName: "VEXARIS",
    applicant: "Bayer AG",
    classes: [5, 10, 44],
    closesAt: "2026-06-08",
    daysLeft: 19,
    status: "open",
    relevant: true,
    watchId: "wl-vexis",
  },
];

window.GAZETTES = [
  { id: "B_T4_2026", issue: "2026 / T4", type: "B", typeLabel: "Registrations", file: "B_T4_2026.pdf", rows: 9499, sizeMB: 233, uploadedAgo: "2 min ago", processed: "6m 28s", status: "completed" },
  { id: "B_T3_2026", issue: "2026 / T3", type: "B", typeLabel: "Registrations", file: "B_T3_2026.pdf", rows: 5326, sizeMB: 157, uploadedAgo: "8 min ago", processed: "2m 22s", status: "completed" },
  { id: "B_T2_2026", issue: "2026 / T2", type: "B", typeLabel: "Registrations", file: "B_T2_2026.pdf", rows: 5913, sizeMB: 181, uploadedAgo: "11 min ago", processed: "2m 44s", status: "completed" },
  { id: "B_T1_2026", issue: "2026 / T1", type: "B", typeLabel: "Registrations", file: "B_T1_2026.pdf", rows: 6608, sizeMB: 121, uploadedAgo: "17 min ago", processed: "3m 14s", status: "completed" },
  { id: "A_T4_2026", issue: "2026 / T4", type: "A", typeLabel: "Applications", file: "A_T4_2026.pdf", rows: 8331, sizeMB: 156, uploadedAgo: "21 min ago", processed: "3m 50s", status: "completed", warning: "OCR confidence 0.82 — 14 rows flagged for review" },
  { id: "A_T3_2026", issue: "2026 / T3", type: "A", typeLabel: "Applications", file: "A_T3_2026.pdf", rows: 3273, sizeMB: 83, uploadedAgo: "28 min ago", processed: "1m 24s", status: "completed" },
  { id: "A_T2_2026", issue: "2026 / T2", type: "A", typeLabel: "Applications", file: "A_T2_2026.pdf", rows: 3159, sizeMB: 82, uploadedAgo: "1 hr ago", processed: "3m 23s", status: "completed" },
  { id: "A_T1_2026", issue: "2026 / T1", type: "A", typeLabel: "Applications", file: "A_T1_2026.pdf", rows: 4649, sizeMB: 91, uploadedAgo: "1 hr ago", processed: "2m 10s", status: "completed" },
];

// Recent searches (yours)
window.RECENT_SEARCHES = [
  { id: "s-1", q: "neur*", scope: "Class 5,10 · VN+SG+IN", count: 24, when: "12 min ago" },
  { id: "s-2", q: "image: NEUREX_logo.png", scope: "Visual sim ≥ 0.75", count: 7, when: "1 hr ago" },
  { id: "s-3", q: "applicant: Masan", scope: "All classes · Last 90 days", count: 18, when: "yesterday" },
  { id: "s-4", q: "vex*", scope: "Class 5 · Worldwide", count: 11, when: "yesterday" },
];

window.CURRENT_USER = { name: "Francis Lam", initials: "FL", role: "Senior Associate", firm: "Trần & Partners IP" };

window.findMark = (id) => window.TRADEMARKS.find(t => t.id === id);
window.classGroup = (n) => (window.NICE_CLASSES[n]?.group || "goods");
window.classLabel = (n) => (window.NICE_CLASSES[n]?.label || "—");
