"""trademarks mark_name

Revision ID: 20260624_0028
Revises: 20260624_0027
Create Date: 2026-06-24 12:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20260624_0028"
down_revision: Union[str, None] = "20260624_0027"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("trademarks", sa.Column("mark_name", sa.Text(), nullable=True))
    op.create_index(op.f("ix_trademarks_mark_name"), "trademarks", ["mark_name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trademarks_mark_name"), table_name="trademarks")
    op.drop_column("trademarks", "mark_name")
    # ### end Alembic commands ###
