"""trademarks vn_grant_date

Revision ID: 20260624_0027
Revises: 20260623_0026
Create Date: 2026-06-24 10:52:27.241576

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20260624_0027"
down_revision: Union[str, None] = "20260623_0026"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("trademarks", sa.Column("vn_grant_date", sa.Date(), nullable=True))
    op.create_index(op.f("ix_trademarks_vn_grant_date"), "trademarks", ["vn_grant_date"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trademarks_vn_grant_date"), table_name="trademarks")
    op.drop_column("trademarks", "vn_grant_date")
    # ### end Alembic commands ###
